"""add_emotion_tag_to_diary_entries

Revision ID: 3b56934ec7b0
Revises: de2ccd321715
Create Date: 2026-09-06 10:01:46.401112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b56934ec7b0'
down_revision: Union[str, None] = 'de2ccd321715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_entries', sa.Column('emotion_tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_entries', 'emotion_tag')
    # ### end Alembic commands ###
