"""add_clinical_note_versioning_and_soap

Revision ID: 640f8ebcb6c0
Revises: 65d22d684983
Create Date: 2026-08-25 00:12:05.778905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640f8ebcb6c0'
down_revision: Union[str, None] = '65d22d684983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('version', sa.Integer(), server_default="1", nullable=False))
    op.add_column('clinical_notes', sa.Column('root_note_id', sa.UUID(), nullable=True))
    op.add_column('clinical_notes', sa.Column('parent_note_id', sa.UUID(), nullable=True))
    op.add_column('clinical_notes', sa.Column('is_latest', sa.Boolean(), server_default="true", nullable=False))
    op.add_column('clinical_notes', sa.Column('format_type', sa.String(), server_default="free_text", nullable=False))
    op.add_column('clinical_notes', sa.Column('soap_subjective', sa.Text(), nullable=True))
    op.add_column('clinical_notes', sa.Column('soap_objective', sa.Text(), nullable=True))
    op.add_column('clinical_notes', sa.Column('soap_assessment', sa.Text(), nullable=True))
    op.add_column('clinical_notes', sa.Column('soap_plan', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'clinical_notes', 'clinical_notes', ['root_note_id'], ['id'])
    op.create_foreign_key(None, 'clinical_notes', 'clinical_notes', ['parent_note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinical_notes', type_='foreignkey')
    op.drop_constraint(None, 'clinical_notes', type_='foreignkey')
    op.drop_column('clinical_notes', 'soap_plan')
    op.drop_column('clinical_notes', 'soap_assessment')
    op.drop_column('clinical_notes', 'soap_objective')
    op.drop_column('clinical_notes', 'soap_subjective')
    op.drop_column('clinical_notes', 'format_type')
    op.drop_column('clinical_notes', 'is_latest')
    op.drop_column('clinical_notes', 'parent_note_id')
    op.drop_column('clinical_notes', 'root_note_id')
    op.drop_column('clinical_notes', 'version')
    # ### end Alembic commands ###
