"""add_appointment_triage_and_video

Revision ID: 65d22d684983
Revises: acff3afa3a77
Create Date: 2026-08-24 23:58:40.591915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d22d684983'
down_revision: Union[str, None] = 'acff3afa3a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('preferred_mode', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('consultation_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('location_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('video_room_url', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('chat_session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'chat_sessions', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'chat_session_id')
    op.drop_column('appointments', 'video_room_url')
    op.drop_column('appointments', 'location_notes')
    op.drop_column('appointments', 'consultation_type')
    op.drop_column('appointments', 'preferred_mode')
    # ### end Alembic commands ###
