"""make_alert_id_nullable_and_add_link_url_to_notifications

Revision ID: b2ee7167114b
Revises: 07fb42b9f757
Create Date: 2026-09-07 14:43:15.476879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ee7167114b'
down_revision: Union[str, None] = '07fb42b9f757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_records', sa.Column('link_url', sa.String(length=512), nullable=True))
    op.alter_column('notification_records', 'alert_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'unsubscribed_from_communications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'unsubscribed_from_communications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notification_records', 'alert_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notification_records', 'link_url')
    # ### end Alembic commands ###
