"""add_alert_sla_and_escalation_tier

Revision ID: bc0b86e173a5
Revises: 640f8ebcb6c0
Create Date: 2026-08-25 00:27:07.941819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0b86e173a5'
down_revision: Union[str, None] = '640f8ebcb6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_alerts', sa.Column('assigned_doctor_id', sa.UUID(), nullable=True))
    op.add_column('risk_alerts', sa.Column('sla_minutes', sa.Integer(), server_default='15', nullable=False))
    op.add_column('risk_alerts', sa.Column('sla_due_at', sa.DateTime(), nullable=True))
    op.add_column('risk_alerts', sa.Column('sla_breached', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('risk_alerts', sa.Column('escalation_tier', sa.Integer(), server_default='1', nullable=False))
    op.add_column('risk_alerts', sa.Column('escalation_history', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'risk_alerts', 'users', ['assigned_doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_alerts', type_='foreignkey')
    op.drop_column('risk_alerts', 'escalation_history')
    op.drop_column('risk_alerts', 'escalation_tier')
    op.drop_column('risk_alerts', 'sla_breached')
    op.drop_column('risk_alerts', 'sla_due_at')
    op.drop_column('risk_alerts', 'sla_minutes')
    op.drop_column('risk_alerts', 'assigned_doctor_id')
    op.alter_column('clinical_notes', 'format_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'free_text'::character varying"),
               existing_nullable=False)
    op.alter_column('clinical_notes', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('clinical_notes', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    # ### end Alembic commands ###
