"""add_tracing_spans

Revision ID: da7207530014
Revises: f072cfaf804041029a46ca7b7f71c971
Create Date: 2026-08-24 03:21:54.169306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7207530014'
down_revision: Union[str, None] = 'f072cfaf804041029a46ca7b7f71c971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracing_spans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('span_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracing_spans_message_id'), 'tracing_spans', ['message_id'], unique=False)
    op.add_column('vr_sessions', sa.Column('time_in_scene', sa.Float(), nullable=True))
    op.add_column('vr_sessions', sa.Column('interaction_count', sa.Integer(), nullable=True))
    op.add_column('vr_sessions', sa.Column('completion_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vr_sessions', 'completion_status')
    op.drop_column('vr_sessions', 'interaction_count')
    op.drop_column('vr_sessions', 'time_in_scene')
    op.drop_index(op.f('ix_tracing_spans_message_id'), table_name='tracing_spans')
    op.drop_table('tracing_spans')
    # ### end Alembic commands ###
