"""add_diary_pin_hash_to_user

Revision ID: db488b851616
Revises: 3b56934ec7b0
Create Date: 2026-09-06 10:31:59.336225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db488b851616'
down_revision: Union[str, None] = '3b56934ec7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('diary_pin_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'diary_pin_hash')
    # ### end Alembic commands ###
