"""add_comment_threading

Revision ID: ef5564aa75c9
Revises: da7207530014
Create Date: 2026-08-24 04:43:22.936724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5564aa75c9'
down_revision: Union[str, None] = 'da7207530014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'community_comments', 'community_comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_comments', type_='foreignkey')
    op.drop_column('community_comments', 'parent_id')
    # ### end Alembic commands ###
